
POST http://localhost:1234/signup
Content-Type: application/json

{
    "id":3,
    "name":"Captain",
    "email":"captain@gmail.com",
    "password":"captain@2005"
}
###
POST http://localhost:1234/login
Content-Type: application/json

{
    "email":"kalaipriyan7777@gmail.com",
    "password":"Kalai@2005"
}
###
POST http://localhost:1234/trylogin
Content-Type: application/json

{
    "email":"kalaipriyan7777@gmail.com",
    "password":"Kalai@2005"
}

####

POST http://localhost:1234/events
Content-Type: application/json

{
    
    "title":"Movie",
    "date":"2020-04-05",
    "description":"Movie",
    "venue":"thetre",
    "total_tickets":"100",
    "available_tickets":"200",
    "price":"200"
}


###
GET http://localhost:1234/regList

###
GET http://localhost:1234/regList

###
GET http://localhost:1234/adminDetails


###
POST http://localhost:1234/booking
Content-Type: application/json

{
    "number":170,
    "name":"Danush",
    "email":"danush@gmail.com",
    "mobile":098765432
}

###
POST http://localhost:1234/signup
Content-Type: application/json

{
    "name":"kanish",
    "email":"kanish@gmail.com",
    "password":"kanish@2007"
}


