
POST http://localhost:1234/signup
Content-Type: application/json

{
    "id":3,
    "name":"Captain",
    "email":"captain@gmail.com",
    "password":"captain@2005"
}
###
POST http://localhost:1234/login
Content-Type: application/json

{
    "email":"kalaipriyan7777@gmail.com",
    "password":"Kalai@2005"
}