
POST http://localhost:1234/signup
Content-Type: application/json

{
    "id":3,
    "name":"Captain",
    "email":"captain@gmail.com",
    "password":"captain@2005"
}
###
POST http://localhost:1234/login
Content-Type: application/json

{
    "email":"kalaipriyan7777@gmail.com",
    "password":"Kalai@2005"
}
###
POST http://localhost:1234/trylogin
Content-Type: application/json

{
    "email":"kalaipriyan7777@gmail.com",
    "password":"Kalai@2005"
}

####

POST http://localhost:1234/events
Content-Type: application/json

{
    
    "title":"Movie",
    "date":"2020-04-05",
    "description":"Movie",
    "venue":"thetre",
    "total_tickets":"100",
    "available_tickets":"200",
    "price":"200"
}